export const STREAM_IDLE_ABORT_MARKER = "CODEFLOW_STREAM_IDLE_TIMEOUT";
export const BASH_TIMEOUT_ABORT_MARKER = "CODEFLOW_EXECUTION_TIMEOUT";
export const CONTEXT_BUDGET_ABORT_MARKER = "CODEFLOW_CONTEXT_BUDGET_EXCEEDED";
